(()=>{
const $=id=>document.getElementById(id),notice=$('notice'),registerForm=$('registerForm'),loginForm=$('loginForm');let client=null;
function showNotice(m,t=''){notice.textContent=m;notice.className='notice '+t;notice.hidden=false}
function clearNotice(){notice.hidden=true;notice.textContent=''}
function setTab(which){const r=which==='register';registerForm.hidden=!r;loginForm.hidden=r;$('registerTab').classList.toggle('active',r);$('loginTab').classList.toggle('active',!r);$('registerTab').setAttribute('aria-selected',String(r));$('loginTab').setAttribute('aria-selected',String(!r));clearNotice()}
$('registerTab').onclick=()=>setTab('register');$('loginTab').onclick=()=>setTab('login');$('goLogin').onclick=()=>setTab('login');$('goRegister').onclick=()=>setTab('register');
function getClient(){if(client)return client;const u=window.CSC_GONE_SUPABASE_URL,k=window.CSC_GONE_SUPABASE_ANON_KEY;if(!window.supabase||!u||!k||u.includes('PASTE_')||k.includes('PASTE_'))throw Error('Setup is not finished. Add your Supabase Project URL and anon/public key in config.js, then reload.');client=window.supabase.createClient(u,k);return client}
function friendlyError(e){const m=e?.message||'Something went wrong. Please try again.';if(/already registered|already exists|user already/i.test(m))return 'This Gmail address may already be registered. Please log in.';if(/invalid login credentials/i.test(m))return 'Gmail address or password is incorrect.';if(/email.*disabled|email provider/i.test(m))return 'Enable the Email provider in Supabase Authentication settings.';return m}
registerForm.addEventListener('submit',async e=>{e.preventDefault();clearNotice();const b=$('registerButton');b.disabled=true;b.textContent='Creating account…';try{const sb=getClient(),name=$('fullName').value.trim(),mobile=$('regMobile').value.trim(),email=$('regEmail').value.trim().toLowerCase(),password=$('regPassword').value;if(name.length<2)throw Error('Enter your full name.');if(!/^[0-9+()\s-]{10,18}$/.test(mobile))throw Error('Enter a valid mobile number.');const digits=mobile.replace(/\D/g,'');if(digits.length<10||digits.length>13)throw Error('Enter a valid mobile number with 10 to 13 digits.');if(!/^[^\s@]+@gmail\.com$/i.test(email))throw Error('Please enter a valid Gmail address ending in @gmail.com.');if(password.length<8)throw Error('Use a password with at least 8 characters.');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name,mobile_number:mobile}}});if(error)throw error;if(data.session){showNotice('Registration successful. Opening dashboard…','success');location.href='dashboard.html'}else showNotice('Account request submitted. If email confirmation is OFF in Supabase, try logging in. If confirmation is still required, check the Auth settings.','success')}catch(e){showNotice(friendlyError(e),'error')}finally{b.disabled=false;b.textContent='Create account'}});
loginForm.addEventListener('submit',async e=>{e.preventDefault();clearNotice();const b=$('loginButton');b.disabled=true;b.textContent='Logging in…';try{const sb=getClient(),email=$('loginEmail').value.trim().toLowerCase(),password=$('loginPassword').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;location.href='dashboard.html'}catch(e){showNotice(friendlyError(e),'error')}finally{b.disabled=false;b.textContent='Login securely'}})
})();